name = "ReferenceFrames"
uuid = "56b1112d-da24-4db9-a9ea-01ee49b4296f"
authors = ["Brayden Barton <brayden.barton@usu.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
