name = "ReferenceFrames"
uuid = "56b1112d-da24-4db9-a9ea-01ee49b4296f"
authors = ["Brayden Barton <brayden.barton@usu.edu> and contributors"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Quaternion = "74eca876-718d-486b-80f4-5251a73a300f"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
